[pytest]
DJANGO_SETTINGS_MODULE = redot.redot.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *TestCase
python_functions = test_*
addopts = 
    --verbose
    --strict-markers
    --tb=short
    --reuse-db
testpaths = redot/core/tests
