# Generated by Django 5.2.7 on 2025-10-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_remove_conta_id_remove_conta_user_conta_id_conta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id_estado", models.AutoField(primary_key=True, serialize=False)),
                ("nome_estado", models.CharField(max_length=45)),
                ("sigla_estado", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "estado",
            },
        ),
        migrations.CreateModel(
            name="Pesquisa",
            fields=[
                ("id_pesquisa", models.AutoField(primary_key=True, serialize=False)),
                ("nome_pesquisa", models.CharField(max_length=50)),
                ("resultado", models.CharField(max_length=100)),
                ("fonte", models.CharField(max_length=50)),
                ("url_resultado", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "pesquisa",
            },
        ),
        migrations.CreateModel(
            name="TipoPlano",
            fields=[
                ("id_tipo_plano", models.AutoField(primary_key=True, serialize=False)),
                ("nome_tipo_plano", models.CharField(max_length=40)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracao_dias", models.IntegerField()),
            ],
            options={
                "db_table": "tipo_plano",
            },
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                ("id_plano", models.AutoField(primary_key=True, serialize=False)),
                ("data_inicio_plano", models.DateField()),
                ("data_fim_plano", models.DateField()),
                ("ativa", models.BooleanField(default=True)),
                (
                    "id_conta",
                    models.ForeignKey(
                        db_column="id_conta",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.conta",
                    ),
                ),
                (
                    "id_tipo_plano",
                    models.ForeignKey(
                        db_column="id_tipo_plano",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tipoplano",
                    ),
                ),
            ],
            options={
                "db_table": "plano",
            },
        ),
    ]
