/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CadastroUsuario: typeof import('./components/CadastroUsuario.vue')['default']
    DemonstracaoRadar: typeof import('./components/DemonstracaoRadar.vue')['default']
    EfetuarPagamento: typeof import('./components/EfetuarPagamento.vue')['default']
    Faq: typeof import('./components/Faq.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PlanosPagamentos: typeof import('./components/PlanosPagamentos.vue')['default']
    Radar: typeof import('./components/Radar.vue')['default']
    RadarSemIdentificacao: typeof import('./components/Radar.vue')['default']
    Realizado: typeof import('./components/Realizado.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SobreNos: typeof import('./components/SobreNos.vue')['default']
    TelaLogin: typeof import('./components/TelaLogin.vue')['default']
    TesteRadar: typeof import('./components/TesteRadar.vue')['default']
  }
}
