# Generated by Django 5.2.7 on 2025-10-27 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conta",
            name="id",
        ),
        migrations.RemoveField(
            model_name="conta",
            name="user",
        ),
        migrations.AddField(
            model_name="conta",
            name="id_conta",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="conta",
            name="id_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="id_usuario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conta",
            name="senha",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="conta",
            name="login",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name="conta",
            table="conta",
        ),
    ]
