# Generated by Django 5.2.7 on 2025-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_conta_id_remove_conta_user_conta_id_conta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="senha",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
